# Generated by Django 5.2.3 on 2025-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
