# Generated by Django 5.2.3 on 2025-09-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problemsolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests_problems', to='problems.problem'),
        ),
        migrations.CreateModel(
            name='ProblemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_title', models.CharField(max_length=200)),
                ('variant_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='problems.problem')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
