# Generated by Django 5.2.3 on 2025-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_contest_problems_problemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_ai_source',
            field=models.BooleanField(default=False),
        ),
    ]
