# Generated by Django 5.2.3 on 2025-08-31 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_contestsubmission_language_contestregistration'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problems', models.ManyToManyField(related_name='uploaded_by', to='problems.problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
