# Generated by Django 5.2.3 on 2025-09-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchqueue',
            name='last_ping',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
